### ISSUE TITLE
[QA][ob-team-charts] rancher-monitoring 66.7.1-rancher.10

### ISSUE THREAD

**Issue by mallardduck** [mallardduck/ob-team-charts#1]
### Pull Request

https://github.com/rancher/ob-team-charts/pull/62

### ClusterRepo Config for QA

```yaml
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: ob-team-charts-dpock
spec:
  gitBranch: fix-66.7-grafana
  gitRepo: https://github.com/mallardduck/ob-team-charts
```

### Testing Considerations

After setting up ClusterRepo and letting it sync in, look for and install 66.7.1-rancher.10.

As mentioned this fix is for a chart version regression, which means to verify you should expect to see newer image versions for Grafana related sub-chart. Subsequently you will also see a slightly "newer" looking UI when you check Grafana.

Example:

- kiwigrid should be 1.28.0
- And Grafana's image render image, 3.11.1

This chart also contains a fix for: https://github.com/rancher/ob-team-charts/issues/60
